apiVersion: v1
kind: Namespace
metadata:
  name: scenario-01-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: scenario-01-ns
  name: service-b-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: scenario-01-ns
  name: service-a-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: scenario-01-ns
  name: service-b-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
      version: 0.0.1
  template:
    metadata:
      labels:
        app: service-b
        version: 0.0.1
    spec:
      serviceAccountName: service-b-sa
      containers:
      - name: service-b-co
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: scenario-01-ns
  name: service-b
spec:
  selector:
    app: service-b
    version: 0.0.1
  ports:
  - name: service-b-http-port
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: scenario-01-ns
  name: service-a-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
      version: 0.0.1
  template:
    metadata:
      labels:
        app: service-a
        version: 0.0.1
    spec:
      serviceAccountName: service-a-sa
      containers:
      - name: service-a-co
        image: curlimages/curl
        command: ["/bin/sh"]
        args: ["-c", "while curl http://service-b.scenario-01-ns/uuid; do sleep 1.0; done;"]
